name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
      - run: uv sync
      - run: uv run ruff .
      - run: uv run pytest
      - run: uv run python apps/track-a-b2c-product-advisor/eval.py
